In [1]:
import numpy as np

In [3]:
# 1. Create a null vector of size 10 but the fifth value which is 1.

null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
# 2. Create a vector with values ranging from 10 to 49.

vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8.

matrix = np.arange(9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0].

non_zero_indices = np.nonzero([1,2,0,0,4,0])
print(non_zero_indices)

(array([0, 1, 4], dtype=int64),)


In [21]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

random_array = np.random.rand(10,10)
min_value = random_array.min()
max_value = random_array.max()
print("Random Array:",random_array)
print("Minimum Value:",min_value)
print("Maximum Value:",max_value)

Random Array: [[0.46292546 0.62665886 0.52620262 0.46699641 0.42847897 0.95278748
  0.6234238  0.24239866 0.94028655 0.52864488]
 [0.90434914 0.69467555 0.86719649 0.0613495  0.37160008 0.73235961
  0.7057482  0.18107846 0.78288211 0.11805466]
 [0.67256266 0.3808763  0.39178045 0.9656709  0.19261841 0.26924788
  0.66666843 0.60466962 0.93449194 0.37711514]
 [0.31826425 0.41081726 0.6082701  0.18462645 0.94197029 0.64358104
  0.85784273 0.80627222 0.84806492 0.71205848]
 [0.24130334 0.31110163 0.85596493 0.14480314 0.02973908 0.76688779
  0.25446158 0.46717342 0.49689164 0.87910669]
 [0.33974223 0.26658409 0.52386155 0.80546263 0.79756029 0.25785717
  0.12007738 0.94135343 0.3845797  0.57228913]
 [0.95465838 0.96736002 0.00952126 0.21144925 0.84299339 0.37949001
  0.36043881 0.2355963  0.50969195 0.67519685]
 [0.78314389 0.33261267 0.08018455 0.31524457 0.32121944 0.48164355
  0.24956814 0.33759756 0.81739409 0.48284706]
 [0.92208339 0.12779014 0.11373248 0.29376054 0.72431501 0.5548884

In [24]:
# 6. Create a random vector of size 30 and find the mean value.

random_vector = np.random.rand(30)
mean_value = random_vector.mean()
print("Random Vector:",random_vector)
print("Mean Value:",mean_value)

Random Vector: [0.00400154 0.53490137 0.48793981 0.25662875 0.33512422 0.5511363
 0.45307754 0.35376825 0.97991971 0.49426365 0.58939549 0.70923126
 0.6821196  0.36785524 0.47909559 0.42531045 0.34681808 0.67794216
 0.34345567 0.22874671 0.73640631 0.13552694 0.41209149 0.80679903
 0.619372   0.5218545  0.01374416 0.26211882 0.79481457 0.33572198]
Mean Value: 0.46463937240634096
